### ISSUE TITLE
incorrectly detected code blocks

### ISSUE THREAD

**Issue by matosimi** [mirao/mads#3]
I'm not sure wheter this can be actually solved that easily, but code blocks are not detected well.

I use .proc and .local quite often, sometimes even .local within .local ... and currently it is not possible to collapse whole block... editor just collapses lines under the actual line until it hits new label (or anything that is unindented).

**Comment by mirao** [comment]
Yes, collapsing seems to be dependent on indentation in the inner region. 
Folding markers are defined for some languages only (https://code.visualstudio.com/docs/editor/codebasics#_folding) and I guess it's not possible to define custom folding e.g. between `.local` and `.endl` in ASM file.
Maybe the extension [#region folding for VS Code ](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder)should help, but I didn't try it.

Another approach is MADS possibility to use [labels preceded by white space](http://mads.atari8.info/mads.html#labels) (such labels must end by ":").
So this is a valid code and folding works as expected:
```
.local
 one: .byte 1 ; label preceded by one space
    lda one
    sta 755
.endl
```

**Comment by matosimi** [comment]
Thanks for commenting on my reported issues. I was considering switching from pspad to vscode but I am not even able to set up vscode to provide similar comfort of pspad... Code folding could be deal breaker, but that's not the case.
