### ISSUE TITLE
feature request - different text colors for built-in pseudo commands

### ISSUE THREAD

**Issue by matosimi** [mirao/mads#4]
I'm used to design where dta, run, icl, ins, ini, end, equ commands are rendered in different color (preferably red), it would be nice to enable such option.... to keep instructions color different to pseudo commands.

Complete list (afaik):
DTA
EIF
ELI
ELS
END
EQU
ERT
ICL
IFT
INI
INS
OPT
ORG
RUN

example:
![image](https://user-images.githubusercontent.com/5637705/45106159-3f1cc300-b136-11e8-9f88-d5db3e8a9c55.png)

more can be seen here (its a youtube video):
[![3plex timelapse](https://img.youtube.com/vi/C_o4KfNpmp8/0.jpg)](https://www.youtube.com/watch?v=C_o4KfNpmp8)

**Comment by mirao** [comment]
The grammar doesn't have set colors for groups of instructions or pseudo instructions. I has set only regexp patterns with names for such groups. An they are somehow associated with colors in VSCode (it's not set in my extension).

E.g.

- `ldx` is in group `keyword.other.opcode.6502.legal` and is dark blue (in general it finally depends on color scheme you have set in VSCode)
- `org` is in the group `keyword.other.mem.new` and is dark blue
- `.macro` is in the group `entity.other.attribute-name.macro` and is light blue

Something about it is here:

- https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
- https://code.visualstudio.com/api/extension-guides/color-theme
- https://macromates.com/manual/en/language_grammars

I'll look at it when have some time.

**Comment by matosimi** [comment]
:) i have logged this issue 4 years ago, time flies.

Just close it and forget it.

Cheers.
