### ISSUE TITLE
Add support for new extentions

### ISSUE THREAD

**Issue by MADRAFi** [mirao/mads#5]
Please add support for new file extentions used in Atari programing:
	".rc"
	".a65"
I would also change the desciption from 6502 assembly to MADS

**Comment by mirao** [comment]
- I added `a65` (e.g. it's used in official Mad Assembler project [here](https://github.com/tebe6502/Mad-Assembler/tree/37602549974b07f34f099280fa44bbc8c268368a/examples/compression/nucrunch))
- But I didn't add `rc`. I can see it e.g. [here](https://github.com/MADRAFi/StarVagrant/tree/master/Intro), but it doesn't to be an assembly code, so the grammar wouldn't work
Feel free to create a PR with a new grammar for such extension.
- Changed description to Mad Assembler (it's official project name: https://github.com/tebe6502/Mad-Assembler)
